spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/my_mp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8888