server:
  port: 8081  # 服务器端口号

spring:
  # Redis 配置（Redis相关的配置项）
  data:
    redis:
      # Redis 服务地址（Redis服务器的IP地址或域名）
      host: localhost
      # Redis 服务端端口（Redis服务器监听的端口号）
      port: 6379
      # 连接密码（如果设置了密码）（访问Redis服务器所需的密码，未设置则为空）
      password:
      # 连接超时时间（毫秒）（客户端连接Redis服务器的超时时间，单位为毫秒）
      timeout: 5000ms
      # 数据库索引（0 - 15，默认为0）（Redis支持多个数据库，通过索引区分，范围0-15）
      database: 0
      # 连接池配置（使用 Lettuce）（基于Lettuce客户端的连接池设置）
      lettuce:
        pool:
          # 连接池最大连接数（连接池中允许的最大活跃连接数量）
          max-active: 200
          # 连接池最大阻塞等待时间（负数表示没有限制）（获取连接时的最大等待时间，负数表示无限等待）
          max-wait: -1ms
          # 连接池中最大空闲连接（连接池中允许保持的最大空闲连接数量）
          max-idle: 10
          # 连接池中最小空闲连接（连接池中需要保持的最小空闲连接数量）
          min-idle: 0
          # 空闲连接检测周期（定期检测并清理空闲连接的时间间隔）
          time-between-eviction-runs: